import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head"; // Import Head from next/head
import "./globals.css";





export const metadata: Metadata = {
  title: "CRED - Cards",
  description: "Generated by create next app",
  icons:{
    icon:"https://web-images.credcdn.in/v2/_next/assets/icons/logo.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0" />
        <meta name="theme-color" content="#000000" />
        <meta property="og:type" content="website" />
        <link rel="shortcut icon" type="image/png" href="https://web-images.credcdn.in/v2/_next/assets/icons/logo.png" />
        <title>CRED - Cards</title>
        <meta name="description" content="designed for those who expect nothing less than absolute, frictionless control." />
        <meta content="credit card management. reimagined." property="og:title" />
        <meta content="designed for those who expect nothing less than absolute, frictionless control." property="og:description" />
        <meta content="https://web-images.credcdn.in/v2/_next/assets/images/cards/cm-og-img.jpg" property="og:image" />
        <meta content="summary_large_image" name="twitter:card" />
        <meta content="@CRED_club" name="twitter:site" />
        <meta content="all your money. in one place." name="twitter:title" />
        <meta content="designed for those who expect nothing less than absolute, frictionless control." name="twitter:description" />
        <meta content="https://web-images.credcdn.in/v2/_next/assets/images/cards/cm-og-img.jpg" name="twitter:image" />
        <link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/fallbackImages/hero-fold/hero-fold-desktop-fallback.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/fallbackImages/multi-card/multi-card-fold-fallback.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/fallbackImages/multi-card/mc-fallback.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/unbilled/fallback/unbilled-fold-fallback.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/unbilled/fallback/unbilled-fold-fallback.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/fallbackImages/single-card/single-card-fold-mobile-fallback.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/fallbackImages/single-card/single-card-fold-desktop-fallback-01.jpg?tr=orig,single-card/single-card-fold-desktop-fallback-02.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/fallbackImages/interactions/swipe-fallback.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/fallbackImages/interactions/long-press-fallback.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/fallbackImages/interactions/smart-nav-fallback.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/fallbackImages/interactions/swipe-fallback.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/fallbackImages/interactions/long-press-fallback.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/fallbackImages/interactions/smart-nav-fallback.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/smart-statements/fallback/fallback-1.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/smart-statements/fallback/fallback-2.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/smart-statements/fallback/fallback-3.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/smart-statements/fallback/fallback-4.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/smart-statements/fallback/fallback-5.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/smart-statements/fallback/fallback-6.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/smart-statements/fallback/fallback-7.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/smart-statements/fallback/fallback-1.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/smart-statements/fallback/fallback-2.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/smart-statements/fallback/fallback-3.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/smart-statements/fallback/fallback-4.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/smart-statements/fallback/fallback-5.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/perks/fallback/card-perks-fallback.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/perks/fallback/card-perks-fallback.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/mobile/fallbackImages/cta/cta-fold-mobile-fallback.jpg?tr=orig" media="screen and (max-width: 767px)" as="image" />
<link rel="preload" href="https://web-images.credcdn.in/v2/_next/assets/images/cards/desktop/fallbackImages/cta/cta-fold-desktop-fallback.jpg?tr=orig" media="screen and (min-width: 1025px)" as="image" />
<meta name="next-head-count" content="45" />
<link rel="preload" href="https://web-assets.cred.club/v2/_next/static/css/eacb8193bb5962f6.css" as="style" />
<link rel="stylesheet" href="https://web-assets.cred.club/v2/_next/static/css/eacb8193bb5962f6.css" data-n-g="" />
<noscript data-n-css=""></noscript>  
      </Head>
      <body>
        {children}
      </body>
    </html>
  );
}
